export const formData = {
    dioceses:[
        "Ankole",
        "Bukedi",
        "Bunyoro-Kitara",
        "Busoga",
        "Central Buganda",
        "Central Busoga",
        "East Rwenzori",
        "Kampala",
        "Karamoja",
        "Kigezi",
        "Kinkiizi",
        "Kitgum",
        "Kumi",
        "Lango",
        "Luweero",
        "Madi West Nile",
        "Masindi-Kitara",
        "Mbale",
        "Mityana",
        "Muhabura",
        "Mukono",
        "Namirembe",
        "Nebbi",
        "North Ankole",
        "North Karamoja",
        "North Kigezi",
        "North Mbale",
        "Northern Uganda",
        "Northwest Ankole",
        "Rwenzori",
        "Sebei",
        "Soroti",
        "South Ankole",
        "West Buganda",
        "West Lango Diocese"
    ],
    paymentMethods:[
        "Mobile Money",
        "Airtel Money",
        "Cash",
        "Master Card"
    ],
    membershipTypes:[
        "active member",
        "officer",
        "OG",
        "OB"
    ]
}